### ISSUE TITLE
Website doesn't load: 'AuthAccount' is not defined

### ISSUE THREAD

**Issue by pepsifan92** [ctcode/visual-planner#2]
Hi,

if I open the link https://ctcode.github.io/visual-planner/vp.htm in Google Chrome or Firefox on Windows 10, it works fine. If I open it with Microsoft EDGE on Windows 10, I get the following error and the site doesn't load. 

_Error Log of the EDGE browser console:_
```
SCRIPT1005: SCRIPT1005: Expected '('
vip_oauth.js (277,8)

ReferenceError: 'AuthAccount' is not defined
   at vp_main (https://ctcode.github.io/visual-planner/vp.js:3:2)
   at invoke (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:44:101)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:94:27)
   at n (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:69:31)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:61:496)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:61:116)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:22:4)
   at m.prototype.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:148:336)
   at m.prototype.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:149:40)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js:21:469)
angular.js (14525,11)

SCRIPT5022: gapi.auth2.ExternallyVisibleError: Missing required parameter 'client_id'
cb=gapi.loaded_0 (219,404)
```
Angular doesn't seem to parse its bindings: In Header: `{{settings.banner_text}}` 

The same Problem occurs on Raspberry Pi with Chromium and Firefox ESR, where I actually want to display the site. 

I've tried to accept google's privacy policy, log in the Browser with Google account and disable all extensions of the Browser.

Any ideas what's the problem?

**Comment by ctcode** [comment]
Just a try/catch syntax error which Chrome didn't object to but Edge did. Now fixed on Edge/Win10. Please verify also fixed on the Pi. Thanks.

**Comment by pepsifan92** [comment]
Thank you very much, now it works!
I tested Edge on Win10, Firefox and Chromium on Raspberry Pi: **Fixed.**
